<a href="https://colab.research.google.com/github/hnvikram-vik/datascience/blob/main/Structuring_and_Preparing_Data_for_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# Raw data dictionary
data = {
    'Order_ID': [1001, 1002, 1003, 1004, 1005, 1005, 1006, 1007, 1008, 1009, 1010, 1011],
    ' Region ': ['north', 'South', 'EAST', 'west', 'North', 'North', 'south', 'East', 'WEST', 'north', 'South', 'east'],
    'Category': ['Electronics', 'electronics', 'Furniture', 'furnture', 'Electronics', 'Electronics', 'Office Supplies', 'office supplies', 'Electronics', 'Furniture', 'Electronics', 'Electronics'],
    'Sales': ['$1200', '$850', '$2500', '$1750', '$1200', '$1200', '$300', '$450', '$1100', np.nan, '$950', '$1300'],
    'Quantity': [5, 3, 2, 1, 5, 5, 7, 4, 6, 2, np.nan, 4],
    'Profit': [200, 120, 400, 250, 200, 200, 50, 60, 180, 90, 150, 220],
    'Order_Date': ['01-01-2024', '02-01-2024', '03-01-2024', '04-01-2024', '01-01-2024', '01-01-2024', '05-01-2024', '06-01-2024', '07-01-2024', '08-01-2024', '09-01-2024', '10-01-2024']
}

# Create DataFrame
df = pd.DataFrame(data)

In [2]:
df.head()

   Order_ID  Region      Category  Sales  Quantity  Profit  Order_Date
0      1001    north  Electronics  $1200       5.0     200  01-01-2024
1      1002    South  electronics   $850       3.0     120  02-01-2024
2      1003     EAST    Furniture  $2500       2.0     400  03-01-2024
3      1004     west     furnture  $1750       1.0     250  04-01-2024
4      1005    North  Electronics  $1200       5.0     200  01-01-2024

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    12 non-null     int64
 1    Region     12 non-null     object
 2   Category    12 non-null     object
 3   Sales       11 non-null     object
 4   Quantity    11 non-null     float64
 5   Profit      12 non-null     int64
 6   Order_Date  12 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 804.0+ bytes

In [4]:
df.shape

(12, 7)

In [6]:
df.isnull().sum()

Order_ID      0
 Region       0
Category      0
Sales         1
Quantity      1
Profit        0
Order_Date    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(1)

In [8]:
df.columns = df.columns.str.strip().str.lower()

In [9]:
df.columns

Index(['order_id', 'region', 'category', 'sales', 'quantity', 'profit',
       'order_date'],
      dtype='object')

In [10]:
df = df.drop_duplicates()

In [11]:
df['region'] = df['region'].str.title()
df['category'] = df['category'].str.title()

In [12]:
df['category'] = df['category'].replace('Furnture','Furniture')

In [13]:
df['sales'] = df['sales'].str.replace('$','',regex = False)

In [14]:
df['sales'] = pd.to_numeric(df['sales'])

In [15]:
df['sales'].fillna(df['sales'].mean(),inplace = True)

/tmp/ipykernel_425/984153148.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sales'].fillna(df['sales'].mean(),inplace = True)

In [16]:
df['quantity'].fillna(df['quantity'].mean(), inplace=True)

/tmp/ipykernel_425/2951135440.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['quantity'].fillna(df['quantity'].mean(), inplace=True)

In [17]:
df['sales'] = df['sales'].astype(float)
df['quantity'] = df['quantity'].astype(int)
df['profit'] = df['profit'].astype(float)

In [18]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 0 to 11
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    11 non-null     int64
 1   region      11 non-null     object
 2   category    11 non-null     object
 3   sales       11 non-null     float64
 4   quantity    11 non-null     int64
 5   profit      11 non-null     float64
 6   order_date  11 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(2), object(2)
memory usage: 704.0+ bytes

In [20]:
high_sales = df[df['sales'] > 1000]
high_sales

    order_id region     category   sales  quantity  profit order_date
0       1001  North  Electronics  1200.0         5   200.0 2024-01-01
2       1003   East    Furniture  2500.0         2   400.0 2024-03-01
3       1004   West    Furniture  1750.0         1   250.0 2024-04-01
4       1005  North  Electronics  1200.0         5   200.0 2024-01-01
8       1008   West  Electronics  1100.0         6   180.0 2024-07-01
9       1009  North    Furniture  1160.0         2    90.0 2024-08-01
11      1011   East  Electronics  1300.0         4   220.0 2024-10-01

In [21]:
region_sales = df.groupby('region')['sales'].sum()
print(region_sales)

region
East     4250.0
North    3560.0
South    2100.0
West     2850.0
Name: sales, dtype: float64

In [22]:
category_profit = df.groupby('category')['profit'].sum()
print(category_profit)

category
Electronics        1070.0
Furniture           740.0
Office Supplies     110.0
Name: profit, dtype: float64

In [23]:
sales_array = df['sales'].to_numpy()

In [24]:
updated_sales = sales_array * 1.10

In [25]:
updated_sales[:5]

array([1320.,  935., 2750., 1925., 1320.])